# Generated by Django 5.1.4 on 2024-12-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoNotificationModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('notification_tye', models.CharField(choices=[('email', 'EMAIL'), ('sms', 'SMS'), ('push', 'PUSH'), ('whatsapp', 'WHATSAPP'), ('telegram', 'TELEGRAM'), ('slack', 'SLACK'), ('webhook', 'WEBHOOK')], default='email', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('sent', 'SENT'), ('failed', 'FAILED'), ('cancelled', 'CANCELLED')], default='pending', max_length=50)),
                ('recipient', models.CharField(max_length=255)),
                ('content', models.JSONField()),
                ('metadata', models.JSONField()),
                ('service_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
        ),
    ]
